version: '3'

services:
  citizen:
    container_name: citizen
    image: citizen:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
   #   depends_on:
   #     - mongodb
    
  # mongodb:
  #   image : mongo:latest
  #   container_name: mongodb
  #   volumes:
  #     - ./database:/data/db
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: citizen-admin
  #     MONGO_INITDB_ROOT_PASSWORD: ncjsbkj567GVGHVT6TRFCGVBJB



